### ISSUE TITLE
Math function in ChatGPT is broken? 

### ISSUE THREAD

**Issue by ariestwn** [zeitlings/ayai-gpt-nexus#10]
Hello,

When I try to do math in ChatGPT, it appears that the formula is broken or something.

Here is the result.
<img width="555" alt="image" src="https://github.com/user-attachments/assets/720e8880-2689-4dee-b1ae-3173435c6fe1">

**Comment by zeitlings** [comment]
Hey! The workflow just outputs what the service, viz. ChatGPT, presents it with. In this case it follows your instruction by outputting LaTeX. The [text view](https://www.alfredapp.com/help/workflows/user-interface/text/) can not render LaTeX. You will have to [let the Alfred developers know](https://www.alfredforum.com/) that you would like that feature added.  (It also looks like the markdown lists are not properly handled either.)

For example, Github's markdown supports [mathematical expressions](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions) and can render the models output accordingly:
> **Profit Margin:** $$[\text{Profit Margin} = \frac{\text{Profit}}{\text{Net Revenue}} \times 100]$$ 

You will have to tell ChatGPT to not use LaTeX or suggest a different format for the formulas. That's all outside of the workflow's control.
