### ISSUE TITLE
Openrouter configuration

### ISSUE THREAD

**Issue by jesvtb** [zeitlings/ayai-gpt-nexus#11]
![Screenshot 2024-11-03 at 1 36 56 PM](https://github.com/user-attachments/assets/b5d8c4a0-2d40-48ec-bb88-9c6220541697)

Hi I am having trouble setting up the proxy alternative for openrouter? Are my environment variables input correct (as shown in screenshot)?

**Comment by zeitlings** [comment]
Hey @jesvtb not quite!
Seeing that you've closed the issue already, you probably won't need it anymore, but for anyone else struggling:
take a look at the [wiki#openrouter]( https://github.com/zeitlings/ayai-gpt-nexus/wiki#openrouter) for an example configuration.
