### ISSUE TITLE
Support openrouter via the main config

### ISSUE THREAD

**Issue by a-b** [zeitlings/ayai-gpt-nexus#12]
Thank you for the excellent workflow. Please consider adding https://openrouter.ai support.

**Comment by zeitlings** [comment]
HI @a-b , 
you're welcome and thanks for the suggestion! Could you elaborate on the benefits of having it there?

Managing a frequently changing selection of models would be difficult.  To keep the main workflow configuration clean, avoid outdated options and continual manual adjustments, I prefer keeping the [configuration details for openrouter]( https://github.com/zeitlings/ayai-gpt-nexus/wiki#openrouter) (and any other proxy) in the environment variables for now. I think that servers for a simpler user experience and prevents configuration bloat.
