### ISSUE TITLE
[Feature Request] Persistent search bar

### ISSUE THREAD

**Issue by sbhal** [zeitlings/ayai-gpt-nexus#13]
When typing in Alfred, how to prevent text from disappearing when focus is lost? Can Alfred's search bar be made persistent?
This is especially needed when composing longer queries.

**Comment by zeitlings** [comment]
Hi @sbhal, there is currently no way to achieve that behavior. That's a design choice made by the Alfred developers. If you'd like to see this feature added, you should suggest it on their [forum](https://www.alfredforum.com/)!

**Comment by gaufde** [comment]
> When typing in Alfred, how to prevent text from disappearing when focus is lost? Can Alfred's search bar be made persistent? This is especially needed when composing longer queries.

Have you used either the multi-line prompt in a second window feature, or the Alfred feature where typed text is remembered?

The Alfred settings can be found in `Alfred Preferences > Advanced > History`, check "store typed query" and anything you type will be accessible the next time you open Alfred by pressing the up arrow. If you want you can also check "Show latest query if within 5 minutes" so you don't have to press the up-arrow at all.

The multi-line prompt feature is available while you are chatting with and LLM using Ayai by holding shift + cmd and pressing enter.

Those might improve your experience if you aren't using them already!

**Comment by sbhal** [comment]
@gaufde Indeed `Alfred Preferences > Advanced > History > store typed query` is helpful, but I am using hotkey to invoke `Text View` and it doesn't prefill the previous query.

I used to lose my typed prompts when other apps took focus. Now I use an external editor for long queries to avoid this problem.
