### ISSUE TITLE
How to attach a document?

### ISSUE THREAD

**Issue by grothen** [zeitlings/ayai-gpt-nexus#14]
I'm wondering how to attach a document in the chat? I can't drag anything because the chat window will disappear immediately.

**Comment by zeitlings** [comment]
Hey @grothen 

You have to make use Alfred's [Universal Actions](https://www.alfredapp.com/help/features/universal-actions/) feature to attach documents. Then follow the documentation [here](https://github.com/zeitlings/ayai-gpt-nexus?tab=readme-ov-file#221-universal-action-attach-document).
