### ISSUE TITLE
Cannot use openai compatible proxy

### ISSUE THREAD

**Issue by amadav** [zeitlings/ayai-gpt-nexus#15]
I have an internal proxy that is openai compatible. Seeing this issue:

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2487.7">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 16.0px 0.0px; font: 14.0px 'Helvetica Neue'; color: #000000; color: rgba(0, 0, 0, 0.9)}
span.s1 {font: 14.0px 'SF Pro'}
table.t1 {border-collapse: collapse}
td.td1 {border-style: solid; border-width: 1.0px 1.0px 1.0px 1.0px; border-color: #bfbfbf #bfbfbf #bfbfbf #bfbfbf; padding: 0.0px 5.0px 0.0px 5.0px}
</style>
</head>
<body>

􀇾 [OpenAI>DecodingError>Stream:Proxy] Decoding failure for ChatStreamResponseOpenAI.Type.self. Key <object> not found. Debug description: No value associated with key CodingKeys(stringValue: "object", intValue: nil) ("object"). \| Context coding path: []
--

</body>
</html>

**Comment by zeitlings** [comment]
Hi @amadav 

I need more information. What is in an internal proxy? What is your setup? 
The fact that the response fails to decode suggests that it is not compatible.
