### ISSUE TITLE
Error when connecting to Claude through OpenRouter

### ISSUE THREAD

**Issue by ghost** [zeitlings/ayai-gpt-nexus#2]
Hi @zeitlings , I've been able to use the workflow to access OpenRouter and the _anthropic/claude-3.5-sonnet_ model, but the following error message appears at the end of every output:

```
􀇾 [Decoding Error > Data Corrupted] Cannot initialize StopReasonOpenAI from invalid String value endturn.
Coding Path: [CodingKeys(stringValue: "choices", intValue: nil), JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "finish_reason", intValue: nil)].
```

![image](https://github.com/zeitlings/ayai-gpt-nexus/assets/131688827/e669a844-68b2-410a-98bf-d285865b67a7)

Thanks in advance!

**Comment by ghost** [comment]
And here are the model details from OpenRouter:

![image](https://github.com/zeitlings/ayai-gpt-nexus/assets/131688827/c4b57898-64b7-42a1-9e72-0c89e6a16ae0)

**Comment by zeitlings** [comment]
Hey @glowacky 
In general, the API responses are expected to mirror those of OpenAI *exactly*, including the stop reason.
However, I'll probably add this particular exception. Might take a while to get around to it though.

**Comment by ghost** [comment]
I think you're right – on [this OpenAI page](https://platform.openai.com/docs/guides/text-generation/chat-completions-api), it seems like the equivalent _finish_reason_ would be "stop"

No rush – will be on the lookout for the exception, thanks! 🙏

**Comment by ghost** [comment]
Hi @zeitlings ! Was this resolved? Still getting the error in alpha-4.

It occurred to me that _finish_reason_ could maybe become another environment variable (openai_alternative_proxy_finish_reason). What do you think?

**Comment by zeitlings** [comment]
Hey @glowacky 

Thanks for the suggestion, I think that's a very good idea. The next version will consider the environment variable `openai_alternative_shared_finish_reasons` (a comma separated list) as a fallback where decoding the finish reason initially fails.

**Comment by zeitlings** [comment]
@glowacky alpha.5 is ready to go now. Let me know if everything works as expected!

**Comment by ghost** [comment]
Seems to be working great, thanks!
