### ISSUE TITLE
OK, I see suggested archive keys…but where do you set them?

### ISSUE THREAD

**Issue by Greenysmac** [zeitlings/ayai-gpt-nexus#4]
I tried digging through the various nodes - couldn't figure it out.

Thanks!

**Comment by zeitlings** [comment]
Hey @Greenysmac 
I'm not entirely sure what you're referring to. Are you asking about setting the keyboard shortcut / hotkey to access the archived conversations? If that's the case, you can configure it through the [Hotkey](https://www.alfredapp.com/help/workflows/triggers/hotkey/) object:

<img width="630" alt="gpt-nex-hotkeys" src="https://github.com/user-attachments/assets/456e24b1-3ff4-4a06-a2ab-70a90e510298">

**Comment by Greenysmac** [comment]
That's EXACTLY what I needed to know. I found the info in the doc 

A. Setup

And while I managed to get everything else working…couldn't figure that out. Thanks for teaching me something new about Alfred!

**Comment by zeitlings** [comment]
You're welcome, glad I could help 🤗
