### ISSUE TITLE
Allow universal action to provide custom prompt?

### ISSUE THREAD

**Issue by nabsiddiqui** [zeitlings/ayai-gpt-nexus#6]
Is it possible to allow universal action to have a customizable prompt before the selected text?

**Comment by zeitlings** [comment]
Hey @nabsiddiqui 
You can modify or add new prompts by editing `actions.config.pkl` and build it with pkl or by modifying the `actions.json` directly. Make a backup of your modified files or they will be overwritten when you update the workflow. 

If you don't want to go that route, you can create a new Universal Action object for the workflow, prepend your instruction to the selected text via the Args and Vars utility, and pass it into the final Run Script object of the inference tasks.

Make sure to use the *Follow Instruction* action by setting the related environment variable.
These variables have to be set: 
```
"workflow_program_state" : "generate",
"action_dispatch_id" : "follow.instruction",
"action_payload": "{your_prompt_and_selected_text}"
```

I'm assuming that you know your way around the Alfred workflow builder canvas, but note that if you just make your instruction (prompt) part of the selected text, you can simply use the default *Follow Instruction* action.

**Comment by nabsiddiqui** [comment]
Thank you for the quick follow-up. Unfortunately, I don't currently know my way around the workflow builder to do this, but I will try to learn it soon. My main reason for suggestion is that this is, I believe, the default way for the other ChatGPT workflow in Alfred and Gemini workflow in Raycast.

**Comment by zeitlings** [comment]
Hey @nabsiddiqui 
Ah, do you mean the Universal Action to open the chat window, and not the one for Inference Actions? That I can indeed look into.

**Comment by nabsiddiqui** [comment]
Yes, what I would ideally like is to be able to highlight a bunch of text and open it in Universal Action. Then, have an option to prompt it and open up the chat with the results. 

This is what it is like in the AskGPT workflow when you select text. I am asking it to rewrite like Shakespeare. The reason I would like to use your extension is to use Gemini and other LLMs, which the AskGPT extension does not allow. 

<img width="739" alt="Screenshot 2024-09-09 at 3 34 34 PM" src="https://github.com/user-attachments/assets/a96ba158-8621-4366-8075-8d0286dcee07">

<img width="729" alt="Screenshot 2024-09-09 at 3 35 36 PM" src="https://github.com/user-attachments/assets/466fed39-20fe-4754-a9c4-fdd1ddc9b88d">

**Comment by zeitlings** [comment]
Added to [v1.0.0-alpha.6](https://github.com/zeitlings/ayai-gpt-nexus/releases). Thanks for the suggestion!

**Comment by nabsiddiqui** [comment]
Thank you so much! This is perfect!

**Comment by nabsiddiqui** [comment]
@zeitlings This worked really well for a while, but it doesn't seem to be working anymore. I keep getting "[File System Error] Chat file does not exist." I had grown fairly attached to using it lol.

**Comment by zeitlings** [comment]
Hey @nabsiddiqui 

I can't reproduce the behavior, neither when starting a new conversation (⏎) through the Universal Action, nor when continuing an existing conversation (⌘⏎, with or without already created _chat file_). Can you describe the steps that lead to the error? Did you do something specific? Did you change the workflow in any way? What version are you using? The more info the better!

**Comment by nabsiddiqui** [comment]
@zeitlings I am using the latest version, and I haven't changed the workflow in any way. I have also reinstalled it and deleted it multiple times. This is what I get.

<img width="397" alt="Screenshot 2024-12-20 at 2 10 12 PM" src="https://github.com/user-attachments/assets/64e99853-fdd4-48bf-b803-ce72da0e6a58" />

**Comment by zeitlings** [comment]
¯\\_(ツ)\_/¯

I still can't reproduce the issue, sorry. The best I can suggest is to try to start a new chat with any of the other methods. Is it the same with all of them? You could also try to inspect the workflow cache folder to confirm nothing suspicious is going on there. Like I said, the more info, the better.

**Comment by nabsiddiqui** [comment]
Thank you for the help. I reinstalled Alfred and deleted my preferences. After doing that, I was able to get it to work. Don't know what happened. You can close the issue.
