### ISSUE TITLE
[Off-topic] Alfred Theme

### ISSUE THREAD

**Issue by idr4n** [zeitlings/ayai-gpt-nexus#7]
Thanks a lot for this workflow. It is working great despite being in alpha.

I was wondering if you can share the Alfred theme shown in the screenshots? Thanks in advance!

**Comment by zeitlings** [comment]
Hey @idr4n 
You're welcome! The theme is already available: [here](https://github.com/zeitlings/ayai-gpt-nexus/tree/main/theme).

**Comment by idr4n** [comment]
Awesome! sorry I missed that. Thanks again!
