### ISSUE TITLE
Feature Request: Display the result of inference?

### ISSUE THREAD

**Issue by jesvtb** [zeitlings/ayai-gpt-nexus#8]
Is it possible to add a immediate display of the inference result?

Maybe Large Type, Markdown or Apple Notification?

Love your workflow btw!

**Comment by zeitlings** [comment]
Hey, I've added a visual and an audio cue on completion when the results were copied to the clipboard for the next version. 
Displaying the text separately defeats the purpose of inference actions in my opinion - why not use chat window for those cases? 

If you want to quickly inspect the results, you could also open Alfred, paste, and launch the [large type](https://www.alfredapp.com/help/features/large-type/) feature, i.e. `⌥+space`, `⌘+V`, `⌘+L`.
